# Generated by Django 5.0.9 on 2024-10-15 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tarea', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task_unemunicipio',
            old_name='manufacturer',
            new_name='Departamento',
        ),
    ]
