# Generated by Django 5.0.9 on 2024-10-16 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarea', '0002_rename_manufacturer_task_unemunicipio_departamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeOrigin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Task_TaskTypeCategory_Name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tarea.typeorigin')),
            ],
        ),
        migrations.CreateModel(
            name='Task_Status_Name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tarea.typeorigin')),
            ],
        ),
    ]
